export const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(value);
};

export const formatNumber = (value: number): string => {
  return new Intl.NumberFormat("pt-BR").format(value);
};

export const cities = [
  { id: "1", name: "São Paulo", state: "SP", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -23.5505, longitude: -46.6333 },
  { id: "2", name: "Rio de Janeiro", state: "RJ", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -22.9068, longitude: -43.1729 },
  { id: "3", name: "Belo Horizonte", state: "MG", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -19.9166, longitude: -43.9345 },
  { id: "4", name: "Salvador", state: "BA", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -12.9722, longitude: -38.5014 },
  { id: "5", name: "Curitiba", state: "PR", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -25.4284, longitude: -49.2733 },
  { id: "6", name: "Porto Alegre", state: "RS", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -30.0277, longitude: -51.2287 },
  { id: "7", name: "Brasília", state: "DF", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -15.7801, longitude: -47.9292 },
  { id: "8", name: "Recife", state: "PE", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -8.0539, longitude: -34.8808 },
  { id: "9", name: "Fortaleza", state: "CE", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -3.7172, longitude: -38.5431 },
  { id: "10", name: "Manaus", state: "AM", country: "Brasil", timezone: "America/Sao_Paulo", latitude: -3.1190, longitude: -60.0217 },
];

export const events = [
  {
    id: "evt-001",
    title: "Lollapalooza Brasil 2024",
    description: "O maior festival de música do Brasil com atrações internacionais e nacionais. Três dias de música, arte e cultura com os melhores artistas do mundo.",
    category: "Música",
    city_id: "1",
    city_name: "São Paulo",
    address: "Parque Interlagos, Avenida Interlagos, 2780 - São Paulo, SP",
    latitude: -23.7036,
    longitude: -46.5876,
    date: "2024-03-15",
    time: "18:00",
    endTime: "23:59",
    price: 800,
    tickets_total: 300000,
    tickets_sold: 285000,
    status: "published",
    rating: 4.8,
    image: "/images/evt-001.jpg",
    organizer_name: "Cultura Viva",
    organizer_id: "tenant-001",
    artists: ["The Weeknd", "Dua Lipa", "Anitta", "Pabllo Vittar"],
    cnpj: "12.345.678/0001-90",
  },
  {
    id: "evt-002",
    title: "Rio Summer Festival",
    description: "Festival de música eletrônica na praia de Copacabana com os melhores DJs do Brasil e do mundo.",
    category: "Música",
    city_id: "2",
    city_name: "Rio de Janeiro",
    address: "Praia de Copacabana, Avenida Atlântica - Rio de Janeiro, RJ",
    latitude: -22.9715,
    longitude: -43.1825,
    date: "2024-02-10",
    time: "20:00",
    endTime: "06:00",
    price: 450,
    tickets_total: 100000,
    tickets_sold: 98000,
    status: "published",
    rating: 4.6,
    image: "/images/evt-002.jpg",
    organizer_name: "EventPro Brasil",
    organizer_id: "tenant-002",
    artists: ["Carl Cox", "Richie Hawtin", "Charlotte de Witte"],
    cnpj: "98.765.432/0001-10",
  },
  {
    id: "evt-003",
    title: "BH Tech Summit 2024",
    description: "Conferência de tecnologia e inovação com palestrantes nacionais e internacionais. Networking, palestras e workshops sobre as tendências do mercado tech.",
    category: "Tecnologia",
    city_id: "3",
    city_name: "Belo Horizonte",
    address: "Expominas, Avenida Getúlio Vargas, 1000 - Belo Horizonte, MG",
    latitude: -19.9715,
    longitude: -43.9815,
    date: "2024-04-20",
    time: "09:00",
    endTime: "18:00",
    price: 299,
    tickets_total: 5000,
    tickets_sold: 4200,
    status: "published",
    rating: 4.9,
    image: "/images/evt-003.jpg",
    organizer_name: "TechEvents Inc",
    organizer_id: "tenant-003",
    artists: ["Palestrantes de Tecnologia"],
    cnpj: "55.555.555/0001-55",
  },
  {
    id: "evt-004",
    title: "Festival de Gastronomia de Salvador",
    description: "Celebração da culinária baiana com chefs renomados. Prove os melhores pratos da gastronomia baiana com chefs de renome nacional.",
    category: "Gastronomia",
    city_id: "4",
    city_name: "Salvador",
    address: "Centro de Convenções, Rua Cristóvão Colombo, 2000 - Salvador, BA",
    latitude: -12.9722,
    longitude: -38.5014,
    date: "2024-05-05",
    time: "12:00",
    endTime: "22:00",
    price: 150,
    tickets_total: 2000,
    tickets_sold: 1800,
    status: "published",
    rating: 4.7,
    image: "/images/evt-004.jpg",
    organizer_name: "FestivalHub",
    organizer_id: "tenant-004",
    artists: ["Chefs Baianos"],
    cnpj: "77.777.777/0001-77",
  },
  {
    id: "evt-005",
    title: "Maratona de São Paulo",
    description: "Corrida de rua tradicional que reúne milhares de atletas. Percurso de 42km pela cidade de São Paulo com suporte completo.",
    category: "Esportes",
    city_id: "1",
    city_name: "São Paulo",
    address: "Parque Ibirapuera, Avenida Pedro Álvares Cabral - São Paulo, SP",
    latitude: -23.5852,
    longitude: -46.6576,
    date: "2024-03-01",
    time: "07:00",
    endTime: "12:00",
    price: 120,
    tickets_total: 50000,
    tickets_sold: 50000,
    status: "sold_out",
    rating: 4.9,
    image: "/images/evt-005.jpg",
    organizer_name: "ShowTime Corp",
    organizer_id: "tenant-005",
    artists: ["Atletas Profissionais"],
    cnpj: "99.999.999/0001-99",
  },
  {
    id: "evt-006",
    title: "Expo Arte Contemporânea",
    description: "Mostra de arte contemporânea com artistas brasileiros e internacionais. Exposição de obras de arte moderna e contemporânea.",
    category: "Arte & Cultura",
    city_id: "6",
    city_name: "Porto Alegre",
    address: "Museu de Arte do Rio Grande do Sul, Praça da Alfândega - Porto Alegre, RS",
    latitude: -30.0277,
    longitude: -51.2287,
    date: "2024-06-15",
    time: "14:00",
    endTime: "20:00",
    price: 80,
    tickets_total: 10000,
    tickets_sold: 6500,
    status: "published",
    rating: 4.5,
    image: "/images/evt-006.jpg",
    organizer_name: "MusicLive SA",
    organizer_id: "tenant-006",
    artists: ["Artistas Contemporâneos"],
    cnpj: "11.111.111/0001-11",
  },
  {
    id: "evt-007",
    title: "Fórum de Negócios Sustentáveis",
    description: "Evento corporativo sobre sustentabilidade e inovação nos negócios. Discussões sobre práticas sustentáveis no mercado.",
    category: "Negócios",
    city_id: "1",
    city_name: "São Paulo",
    address: "World Trade Center, Avenida Nações Unidas, 11541 - São Paulo, SP",
    latitude: -23.6185,
    longitude: -46.6925,
    date: "2024-04-10",
    time: "08:00",
    endTime: "17:00",
    price: 599,
    tickets_total: 2000,
    tickets_sold: 1200,
    status: "draft",
    rating: 0,
    image: "/images/evt-007.jpg",
    organizer_name: "Cultura Viva",
    organizer_id: "tenant-001",
    artists: ["Palestrantes de Negócios"],
    cnpj: "12.345.678/0001-90",
  },
  {
    id: "evt-008",
    title: "Festival de Cinema de Curitiba",
    description: "Mostra de cinema com filmes nacionais e internacionais. Apresentação de obras cinematográficas de diversos gêneros.",
    category: "Arte & Cultura",
    city_id: "5",
    city_name: "Curitiba",
    address: "Teatro Guaíra, Rua XV de Novembro, 971 - Curitiba, PR",
    latitude: -25.4284,
    longitude: -49.2733,
    date: "2024-07-20",
    time: "19:00",
    endTime: "22:00",
    price: 50,
    tickets_total: 15000,
    tickets_sold: 0,
    status: "cancelled",
    rating: 0,
    image: "/images/evt-008.jpg",
    organizer_name: "EventPro Brasil",
    organizer_id: "tenant-002",
    artists: ["Cineastas"],
    cnpj: "98.765.432/0001-10",
  },
  {
    id: "evt-009",
    title: "Feira de Educação e Tecnologia",
    description: "Evento educativo com exposições e workshops sobre tecnologia na educação.",
    category: "Educação",
    city_id: "7",
    city_name: "Brasília",
    address: "Centro de Convenções Ulysses Guimarães",
    latitude: -15.7801,
    longitude: -47.9292,
    date: "2024-08-10",
    time: "10:00",
    price: 0,
    tickets_total: 5000,
    tickets_sold: 3200,
    status: "published",
    rating: 4.4,
    image: "/images/evt-009.jpg",
    organizer_name: "TechEvents Inc",
    organizer_id: "tenant-003",
  },
  {
    id: "evt-010",
    title: "Festival de Verão de Fortaleza",
    description: "Festival de música e cultura na praia de Fortaleza.",
    category: "Festival",
    city_id: "9",
    city_name: "Fortaleza",
    address: "Praia de Iracema",
    latitude: -3.7172,
    longitude: -38.5431,
    date: "2024-01-20",
    time: "16:00",
    price: 200,
    tickets_total: 80000,
    tickets_sold: 75000,
    status: "published",
    rating: 4.7,
    image: "/images/evt-010.jpg",
    organizer_name: "FestivalHub",
    organizer_id: "tenant-004",
  },
  {
    id: "evt-011",
    title: "Rio Summer Festival",
    description: "Festival de música eletrônica na praia de Copacabana com os melhores DJs do Brasil e do mundo.",
    category: "Música",
    city_id: "2",
    city_name: "Rio de Janeiro",
    address: "Rua Francisco Real, Nº580 | Padre Miguel - Rio de Janeiro, RJ",
    latitude: -22.8879,
    longitude: -43.4146,
    date: "2026-03-06",
    time: "20:00",
    endTime: "06:00",
    price: 450,
    tickets_total: 100000,
    tickets_sold: 0,
    status: "published",
    rating: 0,
    image: "https://picsum.photos/seed/rio-summer-festival/700/400",
    organizer_name: "EventPro Brasil",
    organizer_id: "tenant-002",
  },
  {
    id: "evt-012",
    title: "Festival de Jazz",
    description: "Noite de Jazz com grandes nomes do cenário nacional e internacional.",
    category: "Música",
    city_id: "1",
    city_name: "São Paulo",
    address: "Av. Paulista, Nº1578 | Bela Vista - São Paulo, SP",
    latitude: -23.5613,
    longitude: -46.6560,
    date: "2026-04-15",
    time: "19:00",
    endTime: "23:00",
    price: 280,
    tickets_total: 5000,
    tickets_sold: 0,
    status: "published",
    rating: 0,
    image: "https://picsum.photos/seed/jazz-festival/700/400",
    organizer_name: "Cultura Viva",
    organizer_id: "tenant-001",
  },
  {
    id: "evt-013",
    title: "Feira Gastronômica",
    description: "Feira com diversas opções de comidas e bebidas de chefs renomados.",
    category: "Gastronomia",
    city_id: "9",
    city_name: "Fortaleza",
    address: "Rua dos Tabajaras, Nº120 | Iracema - Fortaleza, CE",
    latitude: -3.7172,
    longitude: -38.5431,
    date: "2026-03-22",
    time: "12:00",
    endTime: "22:00",
    price: 80,
    tickets_total: 10000,
    tickets_sold: 0,
    status: "published",
    rating: 0,
    image: "https://picsum.photos/seed/gastronomic-fair/700/400",
    organizer_name: "FestivalHub",
    organizer_id: "tenant-004",
  },
  {
    id: "evt-014",
    title: "Show Stand-Up",
    description: "Noite de humor com os melhores comediantes do Brasil.",
    category: "Humor",
    city_id: "3",
    city_name: "Belo Horizonte",
    address: "Rua da Bahia, Nº1148 | Centro - Belo Horizonte, MG",
    latitude: -19.9208,
    longitude: -43.9381,
    date: "2026-04-10",
    time: "21:00",
    endTime: "23:00",
    price: 150,
    tickets_total: 2000,
    tickets_sold: 0,
    status: "published",
    rating: 0,
    image: "https://picsum.photos/seed/stand-up-show/700/400",
    organizer_name: "TechEvents Inc",
    organizer_id: "tenant-003",
  },
];

export const tenants = [
  {
    id: "tenant-001",
    corporate_name: "Cultura Viva",
    plan_type: "enterprise",
    billing_status: "active",
    events_count: 45,
    organizers_count: 12,
    revenue: 1250000,
    created_at: "2023-01-15T10:30:00Z",
  },
  {
    id: "tenant-002",
    corporate_name: "EventPro Brasil",
    plan_type: "pro",
    billing_status: "active",
    events_count: 28,
    organizers_count: 8,
    revenue: 450000,
    created_at: "2023-03-22T14:20:00Z",
  },
  {
    id: "tenant-003",
    corporate_name: "TechEvents Inc",
    plan_type: "enterprise",
    billing_status: "trial",
    events_count: 15,
    organizers_count: 5,
    revenue: 280000,
    created_at: "2023-05-10T09:00:00Z",
  },
  {
    id: "tenant-004",
    corporate_name: "FestivalHub",
    plan_type: "pro",
    billing_status: "overdue",
    events_count: 12,
    organizers_count: 3,
    revenue: 150000,
    created_at: "2023-06-01T18:00:00Z",
  },
  {
    id: "tenant-005",
    corporate_name: "ShowTime Corp",
    plan_type: "basic",
    billing_status: "active",
    events_count: 8,
    organizers_count: 2,
    revenue: 95000,
    created_at: "2023-07-20T11:45:00Z",
  },
  {
    id: "tenant-006",
    corporate_name: "MusicLive SA",
    plan_type: "pro",
    billing_status: "canceled",
    events_count: 22,
    organizers_count: 6,
    revenue: 320000,
    created_at: "2023-08-15T16:00:00Z",
  },
];
